<a href="https://colab.research.google.com/github/RadioJupiter/AngsRepo/blob/main/PyTorch_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("Hello")

Hello


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.2.1+cu121


In [5]:
#Intro to Tensors
#scaler
scaler = torch.tensor(7)
scaler



tensor(7)

In [6]:
scaler.ndim

0

In [7]:
#Get tensor back as Pyton int
scaler.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim #answers how many dimension something has (number of square brackets)

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape #2by2 row total of 4 elements

torch.Size([2, 2])

In [16]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,5,4]]])

In [17]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape #1(outer bracket)is first dimension then 3x3 rows

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [21]:
### Random tensors
#Why random tensors

#Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers to better represent the data.

#Start with random numbers -> look at data -> update random numbers -> look at data-> update

In [22]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7813, 0.3316, 0.8269, 0.2900],
        [0.7406, 0.4975, 0.1063, 0.2308],
        [0.7039, 0.2637, 0.2469, 0.9578]])

In [23]:
random_tensor = torch.rand(1,3, 4)
random_tensor

tensor([[[0.7775, 0.9170, 0.9390, 0.8770],
         [0.5090, 0.0383, 0.0692, 0.0342],
         [0.3820, 0.2143, 0.1534, 0.6051]]])

In [24]:
#Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(0, 11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,#what datatype float _32 or 16
                               device=None,#what device tensor is on
                               requires_grad=False)#whether or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [37]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5694, 0.8592, 0.2911, 0.0294],
        [0.1947, 0.0302, 0.4316, 0.9617],
        [0.3242, 0.8215, 0.5566, 0.9270]])

In [38]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [39]:
some_tensor.size()

torch.Size([3, 4])

In [40]:
#find out details about some tensor (attributes)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.5694, 0.8592, 0.2911, 0.0294],
        [0.1947, 0.0302, 0.4316, 0.9617],
        [0.3242, 0.8215, 0.5566, 0.9270]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [41]:
#datatype, shape and device tensor is on are attributes

from __future__ import division
### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* division
* Matrix Multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
tensor * 10


tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [48]:
# How to multiply Matrices
#mathisfun.com

#https://www.mathsisfun.com/algebra/matrix-introduction.html

#Matrix Multiplication:
# Two main ways of performing multiplication in neural networks and deep learning:
#1. Element-wise multiplication
#2. Matrix multiplication (the dot product)


In [49]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
#Matrix Multiplication by hand
tensor

tensor([1, 2, 3])

In [52]:
1*1 + 2*2 + 3*3

14

In [53]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.9 ms, sys: 23 µs, total: 3.92 ms
Wall time: 7.49 ms


In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 82 µs, sys: 0 ns, total: 82 µs
Wall time: 86.3 µs


tensor(14)

### One of the most common errors in deep learning: shape errors
There are two main rules that performing matrix multiplication nbeeds to satisy:
The inner dimensions must match:

(3,2) @ (3,2) won't work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work


In [55]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
# inner dimensions must match (inner dimension is 2)


In [57]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5845, 0.1401, 0.2034],
        [0.6993, 0.2119, 0.2275],
        [0.2488, 0.0410, 0.0932]])

In [58]:
#shape errors
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])


tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B)# torch.mm(alias) is the same as torch.matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [62]:
#to Fix out shape issues we can manipulate the shape of one of our tensors using a **transpose**

#transpose switches the axes or dimensions of a given tensor

tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [63]:
tensor_B.shape

torch.Size([3, 2])

In [65]:
#transpose switches dimension
torch.mm(tensor_A, tensor_B.T) #B.T is the transposed version resulting in a matrix that has the shape of the outer dimensions

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [66]:
# The matrix multiplication operation wrks when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tnesor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutout shape: {output.shape}")
#torch.mm(tensor_A, tensor_B.T)




Original shapes: tensor_A = torch.Size([3, 2]), tnesor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Outout shape: torch.Size([3, 3])


Outout shape: torch.Size([3, 3]) these are the out dimensions


In [67]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [68]:
#Finding the Min Max Mean and Sum of Tensors (Tensor Aggregation(large number to small number))

# Create a tensor
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [70]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [73]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [74]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [75]:
# Finding the positional Min and Max of Tensors
#Find position in tensor that has the minimum vlaue with argmin()->returns index position of target tensor where the min value occurs

x.argmin()

tensor(0)

In [76]:
x[0]

tensor(0)

In [77]:
x.argmax()

tensor(9)

In [78]:
x[9]

tensor(90)

In [79]:
#Reshaping, Viewing and Stacking Tensors
# Also Squeezing and unsqueezing nd permuting tensors


In [80]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

reshaping: reshapes an input tensor to a defined shape
View- Teturn a view of a n input tensor of certain shape but keeps the same memory as the original tensor
Stacking- combine multiple tensors on top of each other (vstack) or side by side(hstack)
 Squeeze- removes all '1 dimensions' from a tensor
Unsqueeze - add a '1' dimension to a target tensor
Permute- Return a view of the input with dimensions permuted (swapped) in a certain way

In [81]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [82]:
# Add an extra dimension
x_reshaped = x.reshape(1,9) #dimensions must be compatible with original dimensions (trying to change 7 to 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))